replicaCount: 1

image:
  repository: javiertc86/cardano-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

envSecretName: cardano-api-secret

env:
  NODE_ENV: development
  DB_PORT: 5432
  DB_NAME: cexplorer
  DB_DEBUG: false
  NETWORK: testnet
  REDIS_PORT: 6377
  OGMIOS_PORT: 1337
  BUSINESS_TOKEN_NAME: "TANGO"
  SUBMIT_EVENTBUS_NAME: "cardano-submit-stage"
  SCYLLA_CONTACT_POINTS: '["scylladb"]'
  SCYLLA_KEYSPACE: "cardanodb"
  SCYLLA_LOCAL_DATA_CENTER: "datacenter1"
  THROTTLE_LIMIT: 10
  THROTTLE_INTERVAL: 1000
  # secret
  # DB_HOST: 135.181.203.83
  # DB_USER: postgres
  # DB_PWD: v8hlDV0yMAHHlIurYupj
  # REDIS_HOST: 192.168.1.125
  # OGMIOS_HOST: 135.181.203.83
  # BUSINESS_ADDRESS: addr_test1qpc6srdq6jjt6eetstw6t4elmypvepa6ykxcps3dvvv4fr5ca6s0m36w9nlk7ntwdhvhxeyz9u4lngn97fcv4ykjqc2sk4hrgy
  # BUSINESS_POLICY_ID: 581180fd4d301e925c123e3f1fe78cee670369bf4cca4a9ff3e564d7
  # BUSINESS_POLICY_SCRIPT: '{"type":"all","scripts":[{"type":"sig","keyHash":"8e1cabc60001e3dba8cbba922d804282f161caa93019dcf38d785d36"},{"type":"sig","keyHash":"10e327f6e5aaf7647dbd0bac71c166238573e7046459d2158798d1cb"}]}'
  # BUSINESS_POLICY_SCRIPT_KEYS: '["xprv1azat96jpx7jfu2k2kdtagmtjt9fttypn29mktm3zd9tj6q5754fn9vpgkk8av23a3zeaszszmwfkq2lzj6s866dveuhd5vf8wa4lr4ukyyqmtuhysde3hagyrkvqhmdyu9e7eaznevwyttlxtd0e84j0tg65q8kw","xprv1lzxurvslxtdpkutc3crupg9casz36pmptxm3k8n6ays2lcr6dd9g472vnymkdf9at7l9frw870c8z9a3cj7u4a2942wfnk889kxde8mef037q3eg7qtptgjfwe72w7kmt6mpzrhgkrpxtsydrzmrzsf3qckqrpqq"]'

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}