apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cardano-api-helm-chart.fullname" . }}
  labels:
    {{- include "cardano-api-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cardano-api-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cardano-api-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["npm", "run", "start:dev"]  # Ensure this command is correct
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: DB_USER
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: DB_PWD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: REDIS_HOST
            - name: OGMIOS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: OGMIOS_HOST
            - name: BUSINESS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: BUSINESS_ADDRESS
            - name: BUSINESS_POLICY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: BUSINESS_POLICY_ID
            - name: BUSINESS_POLICY_SCRIPT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: BUSINESS_POLICY_SCRIPT
            - name: BUSINESS_POLICY_SCRIPT_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecretName }}
                  key: BUSINESS_POLICY_SCRIPT_KEYS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-volume
              mountPath: /opt/node_app/app/
      volumes:
        - name: app-volume
          emptyDir: {}